import { mergeParams } from './params'
import type { StoryPage } from './types'

export const storyPages: StoryPage[] = [
  /* ── 0  Origin ── */
  {
    id: 'origin',
    label: '00',
    title: 'In the beginning, a shape\n最初，一个形状',
    text: 'Before it is named, before it is known — a form exists. Perfectly round, perfectly silent. It could become anything.\n在被命名之前，在被认识之前——一个形体已经存在。浑圆，沉默。它可以成为任何东西。',
    imageGradient: 'transparent',
    imageShape: 'circle',
    params: mergeParams({
      height: 1.0,
      width: 1.0,
      maxWidthHeight: 0.5,
      bottomRadius: 0.1,
      bottomDepth: 0.0,
      topRadius: 0.1,
      topDepth: 0.0,
      cubicRatio: 0.6,
      leafEnabled: false,
      biteEnabled: false,
      rotationY: 0.3,
    }),
  },

  /* ── 1  Nature ── */
  {
    id: 'nature',
    label: '01',
    title: 'Nature gives it a name\n自然为它命名',
    text: 'Gravity pulls the poles inward. The equator swells. Dimples form at top and bottom — not as flaws, but as identity. Now it is unmistakably an apple.\n重力将两极向内拉拽，赤道膨胀隆起。顶部和底部形成凹陷——不是缺陷，而是身份。现在，它毫无疑问是一颗苹果。',
    imageGradient: 'transparent',
    // imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop&crop=center', 
    // imageGradient: 'linear-gradient(160deg, #2d5016 0%, #4a7c23 30%, #6ba33a 60%, #8bc34a 100%)',

    imageShape: 'apple',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: false,
      leafLength: 0.18,
      leafWidth: 0.06,
      leafAngle: Math.PI / 3,
      biteEnabled: false,
      rotationY: 1.1,
    }),
  },

  /* ── 2  Tree ── */
  {
    id: 'tree',
    label: '02',
    title: 'It grows upward\n它向上生长',
    text: 'A leaf unfolds at the crown. The apple remembers the branch it hung from, the direction it faced.\n一片叶子在顶端展开。苹果记得它悬挂的枝条，记得它朝向的方向。',
    // imageGradient: 'linear-gradient(to bottom, #87ceeb 0%, #87ceeb 40%, #4a7c23 40%, #2d5016 100%)',
    imageGradient: 'transparent',
    imageShape: 'leaf',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: true,
      leafLength: 0.6,
      leafWidth: 0.3,
      leafAngle: Math.PI / 3,
      biteEnabled: false,
      rotationY: 1.1,
    }),
  },

  /* ── 3  Newton ── */
  {
    id: 'newton',
    label: '03',
    title: 'Then it falls\n然后它落下了',
    text: 'Woolsthorpe Manor, 1666. An apple detaches from a branch and drops to the ground. Isaac Newton watches it fall. In that ordinary moment, gravity becomes visible.\n伍尔索普庄园，1666年。一颗苹果脱离枝头，坠向地面。艾萨克·牛顿注视着它的下落。在那个平凡的瞬间，万有引力变得可见。',
    // imageGradient: 'linear-gradient(to bottom, #1a1a2e 0%, #16213e 30%, #0f3460 60%, #533483 100%)',
    imageGradient: 'transparent',
    imageShape: 'newton',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: true,
      leafLength: 0.6,
      leafWidth: 0.3,
      leafAngle: Math.PI / 3,
      biteEnabled: false,
      rotationY: 1.1,
    }),
  },

  /* ── 4  Knowledge / Bite ── */
  {
    id: 'knowledge',
    label: '04',
    title: 'A bite\n咬一口',
    text: 'From the Garden of Eden to Cupertino, the bite is humanity\'s signature on nature. It says: I was here. I chose to know.\n从伊甸园到库比蒂诺，咬痕是人类在自然上留下的签名。它说：我来过。我选择了知晓。',
    // imageGradient: 'linear-gradient(135deg, #1a472a 0%, #2d6a4f 30%, #40916c 60%, #95d5b2 100%)',
    imageGradient: 'transparent',
    imageShape: 'garden',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: true,
      leafLength: 0.6,
      leafWidth: 0.3,
      leafAngle: Math.PI / 3,
      biteEnabled: true,
      rotationY: 1.1,
      biteU: 0.25,
      biteV: 0.5,
      biteRadius: 0.15,
    }),
  },

  /* ── 5  Jobs / Logo ── */
  {
    id: 'jobs',
    label: '05',
    title: 'Someone saw a logo\n有人看见了一个标志',
    text: '1977. Steve Jobs needed a symbol. Rob Janoff drew an apple with a bite taken out — so no one would mistake it for a cherry. That single bite made it forever recognizable.\n1977年。史蒂夫·乔布斯需要一个符号。罗布·简诺夫画了一颗被咬了一口的苹果——这样就不会有人把它误认为樱桃。那一口让它从此永远可辨。',
    // imageGradient: 'linear-gradient(135deg, #1d1d1f 0%, #2c2c2e 50%, #3a3a3c 100%)',
    imageGradient: 'transparent',
    imageShape: 'logo',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: true,
      leafLength: 0.9,
      leafWidth: 0.45,
      leafAngle: Math.PI / 3+0.1,
      biteEnabled: true,
      rotationY: 3,
      biteU: 0.60,
      biteV: 0.6,
      biteRadius: 0.10,
    }),
  },

  /* ── 6  Vessel ── */
  {
    id: 'vessel',
    label: '06',
    title: 'Form becomes function\n形式成为功能',
    text: 'The skin that once protected flesh now defines space. The shell reveals what was always inside — a hollow waiting to hold something new.\n曾经保护果肉的表皮，现在定义了空间。壳体揭示了一直存在于内部的东西——一个等待承载新事物的空腔。',
    // imageGradient: 'linear-gradient(to bottom, #f5e6d0 0%, #e8c9a0 30%, #c2885a 60%, #8b5e34 100%)',
    imageGradient: 'transparent',
    imageShape: 'vessel',
    params: mergeParams({
      height: 0.95,
      width: 1.05,
      maxWidthHeight: 0.53,
      bottomRadius: 0.22,
      bottomDepth: 0.19,
      topRadius: 0.3,
      topDepth: 0.2,
      cubicRatio: 0.5,
      leafEnabled: false,
      leafLength: 0.18,
      leafWidth: 0.06,
      leafAngle: Math.PI / 3,
      biteEnabled: true,
      rotationY: 1.1,
      biteU: 0.25,
      biteV: Math.PI / 2,
      biteRadius: 0.4,
    }),
  },

  /* ── 7  Variation (random) ── */
  {
    id: 'variation',
    label: '07',
    title: 'It doesn\'t end here\n它不会止步于此',
    text: 'The same parametric rules can drift somewhere unexpected. Each variation is a cousin in the same family — shaped by the same grammar, yet entirely its own.\n同一套参数规则可以漂移到意想不到的地方。每一个变体都是同族的近亲——由相同的语法塑造，却完全属于自己。',
    // imageGradient: 'conic-gradient(from 45deg, #c44a30, #e8a87c, #5e8d38, #4a7c23, #c44a30)',
    imageGradient: 'transparent',
    imageShape: 'random',
    random: true,
  },

  /* ── 8  Playground (free edit) ── */
  {
    id: 'playground',
    label: '08',
    title: 'Now it\'s yours\n现在它是你的了',
    text: 'The story steps back. Every parameter is exposed. Shape it, break it, make it something no one has seen before.\n故事退场。所有参数都已展露。塑造它，打破它，让它成为从未有人见过的东西。',
    // imageGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    imageGradient: 'transparent',
    imageShape: 'play',
    freeEdit: true,
  },
]
